name: "Deploy to Vercel"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    env:
      PRODUCTION: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - run: git ls-tree HEAD | awk '$2 == "commit" { printf "::set-output name=%s_ref::%s\n", $4, $3 }'
        id: inspect-submodules
      - uses: actions/checkout@v2
        with:
          repository: urdh/photography-collections
          path: collections
          ref: ${{ steps.inspect-submodules.outputs.collections_ref }}
          ssh-key: ${{ secrets.SSH_KEY }}
          lfs: true
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack
      - run: stack build
      - run: stack exec site build
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: --confirm ${{ (env.PRODUCTION == 'true') && '--prod' || '' }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./_site
      - run: curl -s https://google.com/ping\?sitemap=https://photography.sigurdhsson.org/sitemap.xml
        if: ${{ success() && (env.PRODUCTION == 'true') }}
